### ISSUE TITLE
Odd behavior on values ending in `.`

### ISSUE THREAD

**Issue by alexraginskiy** [doowb/group-array#11]
Grouped values ending in a period create unexpected results, with an intermediary grouping for an empty string. Periods in the middle of the value have no effect, as expected.

Input without trailing `.`:
```javascript
groupArray(
  [{ name: 'foo', value: 1 }, { name: 'foo.bar', value: 2 }],
  'name'
)
```
Output:
```json
{
  "foo": [
    {
      "name": "foo",
      "value": 1
    }
  ],
  "foo.bar": [
    {
      "name": "foo.bar",
      "value": 2
    }
  ]
}
```

Input **with** trailing `.`:
```javascript
groupArray(
  [{ name: 'foo', value: 1 }, { name: 'foo.bar.', value: 2 }], 
  'name'
)
```
Output:
```json
{
  "foo": [
    {
      "name": "foo",
      "value": 1
    }
  ],
  "foo.bar\\": {
    "": [
      {
        "name": "foo.bar.",
        "value": 2
      }
    ]
  }
}
```

**Comment by doowb** [comment]
Thanks for the examples. I'll try to look into this as soon as I can (it might not be until the weekend though). If you discover anything before that, please let me know.

**Comment by GlennKintscher** [comment]
@doowb Any updates on this? I am facing the same problem

Edit: I created a PR in the repo of the library that causes the problem.

**Comment by doowb** [comment]
A PR on another library closed this issue. I'm reopening it until I can test it out to see if anything else is necessary here.

**Comment by GlennKintscher** [comment]
@doowb I created the PR specifically for this issue and it works fine with the changes, so there should nothing to do be left :)

**Comment by doowb** [comment]
@GlennKintscher thanks for the PR!

I just wanted to make sure that the `group-array` dependencies were correct after `set-value` was published.

It all looks good and I added a test here to verify that it works correctly, so I'll close this now.

Thanks again!
