### ISSUE TITLE
Does not work when values are numbers

### ISSUE THREAD

**Issue by cperryk** [doowb/group-array#4]
This doesn't work when the values of the specified property are numbers. Is this intentional?

Here's the relevant piece of code in `groupBy`:

```
    if (typeof val === 'string') {
      groups[val] = groups[val] || [];
      groups[val].push(obj);
    } else if (typeOf(val) === 'object') {
      groupObject(groups, obj, val);
    } else if (Array.isArray(val)) {
      groupArray(groups, obj, val);
    } else if (typeOf(val) === 'function') {
      throw new Error('group-array expects group keys to be strings, objects or undefined: ' + key);
    }
```

This could be fixed just by adding a `typeof === 'number'` check to that first conditional.

**Comment by doowb** [comment]
> This doesn't work when the values of the specified property are numbers

Thanks for pointing this out. Do you have an example code snippet showing this bug?
It probably is just a case of supporting numbers in the conditional, but I'd like to have a test for it.

If you'd like to submit a PR with the test and fix, I'd appreciate it, otherwise I'll try to get to it later.
