### ISSUE TITLE
New dependencies has different behavior and broke dependent libraries

### ISSUE THREAD

**Issue by eon8** [doowb/group-array#6]
After "optimizations" commit (https://github.com/doowb/group-array/commit/bcca097327d7915971490c693e2e4e29bd309d99) if property, which is used for grouping array items has a dot inside, it is considered as a nested object property.

Instead of: `{"a.b": "value"}` we recieve `{"a": {"b": "value"}}`

This for example broke gulp-inject functionality, which I encountered. It uses group-array to group objects by filename. The dot before extension inside filepath is now considered as a nested object key separator and the library doesn't work as expected.

**Comment by jonschlinkert** [comment]
this is a regression. we'll get this fixed

related https://github.com/klei/gulp-inject/issues/219

**Comment by doowb** [comment]
@eon8 this should be fixed now. I'm going to close this issue, but feel free to re-open if you're still having problems.
