### ISSUE TITLE
groupArray doesn't find the key if the value is a boolean

### ISSUE THREAD

**Issue by pezzullig** [doowb/group-array#7]
Great package by the way, just wondering if i am doing something wrong but i have the following problem, in ES6
    
```
    const test = [{ boolean: true, string: 'james' }, { boolean: true, string: 'james' }];
    const test1 = groupArray(test, 'string');
// gives me this: 
{
    "james": [
      {
        "boolean": true,
        "string": "james"
      },
      {
        "boolean": true,
        "string": "james"
      }
    ]
  }
````
which is fine but when i try it for the boolean key it will return an empty object. 
```
    const test = [{ boolean: true, string: 'james' }, { boolean: true, string: 'james' }];
    groupArray(test, 'boolean');

// gives me
 {}
```
It works perfectly for anything that doesn't have true or false as the value. But it can't seem to find a value, 
Thanks for your help

**Comment by doowb** [comment]
Thanks for the example code @pezzullig. I have a fix locally and added tests to cover this scenario. I'm working on fixing #6 then I'll get this published as bug fix.
